
# MIL and TOR
mydict = {
'K Lowry':[15,'PG','TOR'],
'E Bledsoe':[12.5,'PG', 'MIL'],
'G Hill':[9,'PG', 'MIL'],
'F Vanvleet':[5,'PG','TOR'],
'J Lin':[4,'PG','MIL'],
'M Brogdon':[10,'SG','MIL'],
'D Green':[9,'SG','TOR'],
'P Connagauton':[8,'SG','MIL'],
'N Powell':[5,'SG', 'TOR'],
'S Brown':[4.5,'SG','MIL'],
'J Meeks':[4,'SG','TOR'],
'P Mccaw':[4,'SG','TOR'],
'K Leonard':[22,'SF','TOR'],
'K Middeleton':[14.5, 'SF', 'MIL'],
'N Mirotic':[9, 'SF', 'MIL'],
'O Anunoby':[5,'SF','TOR'],
'T Snell':[3.5,'SF','MIL'],
'M Miller':[3.5,'SF','TOR'],
'G Antekounmpo':[23,'PF','MIL'],
'P Siakam':[15,'PF','TOR'],
'E Ilyasova':[8.5,'PF','MIL'],
'D Wilson':[4.5,'PF','MIL'],
'C Boucher':[4,'PF','TOR'],
'M Gasol':[12,'CE','TOR'],
'B Lopez':[10'CE','MIL'],
'S Ibaka':[10,'CE','TOR'],
'E Moreland':[3.5,'CE','TOR'],
}